### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by UniverseStudio324** [GateteVerde/Gatete-Mario-Engine-9#1]
When i want to compile Gatete Mario Engine 9, it errors me.

Script: wtimer at line 35 : Symbol , or ) expected
Script: wtimer at line 35 : Symbol ) expected
Script: wtimer at line 35 : Got '=' expected '{'

Can you fix it???

**Comment by GateteVerde** [comment]
I'll check it later

**Comment by GateteVerde** [comment]
I did compiled a executable just fine, no errors were found.
