### ISSUE TITLE
tileset...

### ISSUE THREAD

**Issue by victor-1984** [GateteVerde/Gatete-Mario-Engine-9#10]
hola no me muestra el piso en ninguno de los niveles, no e tocado absolutamente nada, e bajado un nuevo repositorio y sigue haciendo lo mismo

![IMG_20220910_122324366](https://user-images.githubusercontent.com/67482402/189490633-dbce7ed8-b5bf-4e15-88e2-f92c77af794f.jpg)
![IMG_20220910_122339068](https://user-images.githubusercontent.com/67482402/189490655-88123640-f3de-426c-a197-7f177d1950ec.jpg)
![IMG_20220910_122351902](https://user-images.githubusercontent.com/67482402/189490675-f7ea19d9-09c0-4382-a5db-2383b510259b.jpg)
![IMG_20220910_122446179](https://user-images.githubusercontent.com/67482402/189490695-173b0863-52e8-43b5-a536-4e09a722f29e.jpg)

**Comment by GateteVerde** [comment]
Which version of GameMaker Studio 2 are you using?

It is shown at the top-right corner

**Comment by victor-1984** [comment]
![IMG_20220910_124459474](https://user-images.githubusercontent.com/67482402/189491028-967b9b71-e4fb-4f90-a21c-a07712677db5.jpg)
![IMG_20220910_124508921](https://user-images.githubusercontent.com/67482402/189491049-8aa4a229-61e4-47a4-9e34-1291673bef69.jpg)

**Comment by GateteVerde** [comment]
You need version 2022.8 and above to use it
