### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by mariodad3** [GateteVerde/Gatete-Mario-Engine-9#11]
1:(obj_piranhaplant_side_right)and(obj_piranhaplant_side_left)cant hurt mario:
![image](https://user-images.githubusercontent.com/37357346/192727225-7bc32ee2-b5df-4b0c-a22b-e83caee19f0d.png)
2:raccoon mario cant use tail to open spike qblock and winged qblock
![image](https://user-images.githubusercontent.com/37357346/192730122-6c80b758-6876-4e07-9764-2ee97cefd204.png)

**Comment by GateteVerde** [comment]
Patched on current release
