### ISSUE TITLE
Cannot open the file

### ISSUE THREAD

**Issue by matrix484** [GateteVerde/Gatete-Mario-Engine-9#13]
You have previously mentioned that this engine supports from Game Maker Studio 2022.8 or later. When I try to open the file, it throws an error stating that it cannot open this file.
It shows something like this:

![Screenshot 2023-03-19 214102](https://user-images.githubusercontent.com/101418910/226189380-a7af8274-9b95-4388-a85d-63148e7a4735.jpg)

My GameMaker Version: 2022.0.0.19 (LTS)

**Comment by WinMithul** [comment]
There is some small mistake here, 
My GameMaker Version: 2022.0.0.19 (LTS)

**Comment by GateteVerde** [comment]
I don't use the LTS version of GameMaker, but there's a new version of LTS coming in April from what I seen on the GameMaker Discord

Try forwarding this question in the Discord to see if they can give you a solution.

I can't do anything about this sadly
