### ISSUE TITLE
!THIS IS NOT AN ISSUE! can you give every yoshi color its own ability?

### ISSUE THREAD

**Issue by jipjang123** [GateteVerde/Gatete-Mario-Engine-9#15]
like red yoshi spits fire, even if he didnt eat a red koopa, and blue yoshi can fly if he has something in his mouth, and yellow yoshi stomps if he has something in his mouth.

**Comment by GateteVerde** [comment]
Yoshis have already their own ability and to keep the things loyal to the real game, Yoshis will only get their own ability with koopa shells only
