### ISSUE TITLE
Error Encountered When Finishing a Level w/ Lakitu Cloud/Pidgit Carpet

### ISSUE THREAD

**Issue by drsmigle** [GateteVerde/Gatete-Mario-Engine-9#17]
The game crashes with the following error message when completing a level (tested with flagpole, item card, and goal tape) and riding either Lakitu's cloud or Pidgit's carpet:

___________________________________________
############################################################################################
ERROR in
action number 1
of  Step Event0
for object obj_lakitu_cloud:

Unable to find instance for object index 546
 at gml_Object_obj_lakitu_cloud_Step_0 (line 68) - && (collision_rectangle(bbox_right, obj_mario.bbox_top+4, bbox_right+1+hspeed, obj_mario.bbox_bottom-1, obj_solid, 1, 0)) {
############################################################################################
gml_Object_obj_lakitu_cloud_Step_0 (line 68)

**Comment by GateteVerde** [comment]
Hello, I just identified the issue and I'm patching this now

Patched in r768
