### ISSUE TITLE
My own Level music crashes the game '-' 

### ISSUE THREAD

**Issue by Adinio06** [GateteVerde/Gatete-Mario-Engine-9#19]
So, I'm making my own Mario Game with this Engine right now, and one of the first things that I wanted to do, is to try and add my own music, after I dragged it into the datafiles/music folder, I added into obj_levelcontrol, upon starting the stage it crashed the game ? Can someone please help me 😭 
It also says that an error occured at Alarm 0, Line 21 from obj_levelcontrol.
![17219172268072796214607607047848](https://github.com/user-attachments/assets/3015df2f-7b7b-41d2-9c9e-dcfbadf5ab47)
![17219172505672992632795944716199](https://github.com/user-attachments/assets/383d344e-6086-410e-9f23-0cab3dd490e8)

**Comment by GateteVerde** [comment]
Have you added the file route and loop points it into the .ini file?

The levelcontrol needs to read a .ini file with the info to load it, check the provided entries on it to see how to add it.

**Comment by Adinio06** [comment]
OOOOOH, no I didn't

**Comment by Adinio06** [comment]
![20240725_162851.jpg](https://github.com/user-attachments/assets/73f4ad24-bb9a-4e29-b193-6fd15f6d0713)

You mean this right ?

**Comment by GateteVerde** [comment]
Affirmative

Loop points must go in seconds/hundredths

**Comment by Adinio06** [comment]
THANK YOU SO MUCH, YOUR A LIFE SAVER 😭😭❤️
