### ISSUE TITLE
How i access to the music?

### ISSUE THREAD

**Issue by Coder-M-a** [GateteVerde/Gatete-Mario-Engine-9#20]
I'm making an SMB2 Remake but i can't find the musics folder :(

**Comment by GateteVerde** [comment]
Music is external, you need to put the music in the datafiles folder.

Do find the **Included Files** folder to see how it works

**Comment by Coder-M-a** [comment]
How can I put it in the game?

**Comment by GateteVerde** [comment]
Edit the ini file and add a new section on the level control object

**Comment by Coder-M-a** [comment]
I put the music but when i enter in a level the game crashes but i have an idea put the music play in the room creation code but the ini file are there, how can i ¨delete¨ them without crashing the game? (To is for my remake from Mario 2 wants to have his own music per level and the underground parts) And sorry if i have bad spelling : (

**Comment by GateteVerde** [comment]
In the variables of obj_levelcontrol, add a new list element with the same name you put in the .ini file
