### ISSUE TITLE
Mario has no Star Palette anymore, when I collect the Star Powerup ?

### ISSUE THREAD

**Issue by Adinio06** [GateteVerde/Gatete-Mario-Engine-9#21]
Hey Everyone, I'm currently continuning my Mario Game with your Guys Engine. And later I changed one of Mario's Sprites into mine. When I used it in the Game, it worked flawless. But I noticed that when I collected the Star Powerup, Mario's Coloring wasn't rainbow anymore, the only thing he had was the trail behind him. How can I make this effect on my own sprite again ?

Thanks in Regards
Aldin
![Mario Forgotten Adventures - No Star Coloring](https://github.com/user-attachments/assets/9668d7e0-0a1c-4b7a-b8f9-723ec1a679b8)

**Comment by GateteVerde** [comment]
Mario makes use of a palette, make sure the palette makes the same colours as mario in the first column of the palette

**Comment by Adinio06** [comment]
You mean this one ?
![Palette](https://github.com/user-attachments/assets/83899077-9752-4181-9ac9-f538a648abf8)

**Comment by Adinio06** [comment]
And if yes, what exactly do I need to do next ?

**Comment by Adinio06** [comment]
Or is it the wrong one, do you mean MARIOs Palette or the Starman Palette ?

**Comment by GateteVerde** [comment]
That's the correct one, just make the colours from mario's sprites match with the first column

**Comment by Adinio06** [comment]
Uhhhhh, sorry for asking again, but which do I need to add from Mario the Vertical ones or horizontal and which line do I need to change in the right pic, sorry for askin so much Xd
![Unbenannt](https://github.com/user-attachments/assets/a32c1062-bafd-4e45-aaec-8b7bcdba53cf)

**Comment by Adinio06** [comment]
Can you maybe give me an example from how it was before I changed it ? XD

**Comment by Adinio06** [comment]
Ayyy, sorry for asking again, but I still didnt manage to get it to work, could you maybe give me a like walkthrough video or smth ? Xd

**Comment by GateteVerde** [comment]
Look at the palette sprites, the first column of each sprite has the default colours that both small and big mario use

The shader will apply up the colours from the rest of columns

**Comment by GateteVerde** [comment]
What I mean is, make the colours the sprites of Mario use match with the colours of the leftmost column of each palette

**Comment by Adinio06** [comment]
Bro, Im so sorry, but I cant seem to get it, could we maybe make like a discord call or smth ? I sat on this problem for atleast 2 hours now, cant seem to fix it. :(

**Comment by GateteVerde** [comment]
https://discord.gg/8qKuPWws6R

Create a thread in the gatete-mario-engine-9 section and I'll give you a step by step guide
