### ISSUE TITLE
How does the object: Warp_Block work ?

### ISSUE THREAD

**Issue by Adinio06** [GateteVerde/Gatete-Mario-Engine-9#22]
I wanted to build a level where you first slide down a slope, after going down, you'd enter the Underground, how exactly do I use a warpzone there, how does the object exactly work ?
![image](https://github.com/user-attachments/assets/ab74ae23-1e6a-4bb3-aa0d-573d51d55c1f)
The green bar is the Warp_Block, sadly, I dont know how to use it XD.

**Comment by GateteVerde** [comment]
That object is exclusive to be used only when Mario is climbing, use **obj_pitwarp** instead
