### ISSUE TITLE
Sprite shows up too early

### ISSUE THREAD

**Issue by Adinio06** [GateteVerde/Gatete-Mario-Engine-9#23]
For some reason, in this Level I tried to create, the ?-Block with a mushroom inside, shows the mushroom sprite too early, Idk why, I would love to know what is causing it exactly XD
![image](https://github.com/user-attachments/assets/0271e56b-c0b1-4b74-9a8f-3da454933a26)

**Comment by GateteVerde** [comment]
It is created at the wrong layer, are you using the template?

Check the layers you have on the room

**Comment by Adinio06** [comment]
uhhh yes, basically I created it on the main layer
![image](https://github.com/user-attachments/assets/fba3ac38-09bf-43d7-8e53-3702206525d2)

**Comment by Adinio06** [comment]
I thought at first that it needed to be one of the first objects in the list, but that doesnt seem to be the case.

**Comment by Adinio06** [comment]
So, what do you think ?

**Comment by GateteVerde** [comment]
Oooh, I see the problem

"Main" depth should be 0

**Comment by Adinio06** [comment]
oooh ok, thank you for the quick help, appreciate it ;)

**Comment by Adinio06** [comment]
Yep, that was the problem, thank you so much <3
