### ISSUE TITLE
Game sends me back to Beginning of the Level

### ISSUE THREAD

**Issue by Adinio06** [GateteVerde/Gatete-Mario-Engine-9#24]
So basically, Im creating an Auto-Scroller in a desert Level right ? When I add a Subarea, and exit that Subarea, the game spawns me back to the beginning, is there a way, the level continues the Auto-Scroll from where my Warp_Node is located ?
![image](https://github.com/user-attachments/assets/b6d1f1c5-5b16-44a8-a230-47f2e153686d)
The Black Outlines are the Warp_Node, and Warp_Block are located, the red outline is where the Level spawns me too.

**Comment by GateteVerde** [comment]
I think I did not added anything to make the autoscroller snap into a warp position, I did for the checkpoints tho

**Comment by Adinio06** [comment]
Ok, no problem, thank you for the quick reply tho ;) So basically, when you make an Auto-Scroller, I can't make any subareas that go back to that warp_node. Again, thank you tho :)

**Comment by GateteVerde** [comment]
I might have a solution, but I do need to test it out first

**Comment by GateteVerde** [comment]
Silly me, I forgot!

In both **obj_warp_node** and the checkpoint objects there's a pair of variables called like this:

- scroll_x
- scroll_y

Just edit the scroll_x variable in the nodes or the checkpoints and the camera will automatically pan to the given coordinate of the node, you can just use x or y as wildcard
