### ISSUE TITLE
Got this weird error when starting up my level.

### ISSUE THREAD

**Issue by Adinio06** [GateteVerde/Gatete-Mario-Engine-9#25]
___________________________________________
############################################################################################
ERROR in action number 1
of Draw Event for object obj_viewblock:
draw_sprite argument 1 invalid reference to (sprite) - requested -1 max is 2184
 at gml_Object_obj_viewblock_Draw_0 (line 20) -                draw_sprite(macro_get_sprite(sprout[numb]), 0, round(x)+8, round(y));
############################################################################################
gml_Object_obj_viewblock_Draw_0 (line 20)

I have one Viewblock in my level, it holds 5 items. A mushroom, a fireflower, a star, a 1up and a coin. Why is it giving me the error exactly ?

**Comment by GateteVerde** [comment]
May I see how you have it set on the room?

**Comment by Adinio06** [comment]
![image](https://github.com/user-attachments/assets/77cfe05a-7807-4065-97e2-42351c6407dd)

**Comment by GateteVerde** [comment]
I meant the variables

**Comment by Adinio06** [comment]
![image](https://github.com/user-attachments/assets/baa0ac1f-ac1e-426f-a6f5-72c41dec39ac)

**Comment by GateteVerde** [comment]
Oh, coins cannot be obtained from view blocks

**Comment by Adinio06** [comment]
ah ok, my bad XD
Thanks for the quick help ;)

**Comment by Adinio06** [comment]
Oh man, now I got ANOTHER ERROR, when starting my 2nd level.

**Comment by Adinio06** [comment]
___________________________________________
############################################################################################
ERROR in action number 1
at time step8 of time line <undefined>:
Variable <unknown_object>.rm_course_w1_level2_b(100414, -2147483648) not set before reading it.
 at gml_RoomCC_rm_course_w1_l2_12_PreCreate (line 1) - self.destination=rm_course_w1_level2_b;self.exit_id=1;
############################################################################################
gml_RoomCC_rm_course_w1_l2_12_PreCreate (line 1)

**Comment by Adinio06** [comment]
Nvm, fixed it now XD
