### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by zerrvyx** [GateteVerde/Gatete-Mario-Engine-9#6]
Idk why this happened or how to fix it lol. No edits made btw.
___________________________________________
############################################################################################
ERROR in
action number 1
of Other Event: Game Start
for object obj_coordinator:

unable to convert string "" to number
 at gml_Object_obj_coordinator_Other_2 (line 105) -                      global.button[input.select] = real(file_text_read_string(file));
############################################################################################
gml_Object_obj_coordinator_Other_2 (line 105)

**Comment by GateteVerde** [comment]
The coordinator object was changed on the latest update.

Please delete the "settings.dat" file from the AppData folder to fix
